# Generated by Django 2.1.1 on 2018-09-09 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructions', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=80)),
                ('indicator', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('N', 'Sin Contestar'), ('T', 'Terminado'), ('P', 'Parcialmente contestado')], default='N', max_length=1)),
                ('value', models.SmallIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Instrumento',
                'verbose_name_plural': 'Instrumentos',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='InstrumentApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.SmallIntegerField()),
                ('year', models.CharField(max_length=4)),
                ('status', models.CharField(choices=[('A', 'Activa'), ('I', 'Inactiva')], default='A', max_length=1)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Aplicación de Instrumentos',
                'verbose_name_plural': 'Aplicaciones de Instrumentos',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='InstrumentResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.SmallIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('iapplication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.InstrumentApplication')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Instrument')),
            ],
            options={
                'verbose_name': 'Resultado de Instrumento',
                'verbose_name_plural': 'Resultados de Instrumento',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=80)),
                ('value', models.SmallIntegerField()),
            ],
            options={
                'verbose_name': 'Opción',
                'verbose_name_plural': 'Opciones',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.SmallIntegerField()),
                ('description', models.CharField(max_length=120)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Instrument')),
                ('options', models.ManyToManyField(to='principal.Option')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='instrumentResult',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.InstrumentResult'),
        ),
        migrations.AddField(
            model_name='answer',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Option'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Question'),
        ),
    ]
