# Generated by Django 2.1.1 on 2018-09-09 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instrument',
            old_name='value',
            new_name='maxValue',
        ),
        migrations.AlterField(
            model_name='instrument',
            name='status',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1),
        ),
    ]
