# Generated by Django 2.1.1 on 2018-09-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_auto_20180909_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='instructions',
            field=models.CharField(max_length=350),
        ),
    ]
