# Generated by Django 2.1.1 on 2018-09-11 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0007_auto_20180909_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Nombre(s)')),
                ('lastName', models.CharField(max_length=60, verbose_name='Apellido Paterno')),
                ('mLastName', models.CharField(max_length=60, verbose_name='Apellido Materno')),
                ('birthDate', models.DateField(verbose_name='Fecha de nacimiento')),
                ('civilStatus', models.CharField(choices=[('C', 'Casado(a)'), ('D', 'Divorciado(a)'), ('V', 'Viudo(a)'), ('S', 'Soltero(a)'), ('U', 'Unión Libre')], default='C', max_length=1)),
                ('phase', models.SmallIntegerField(verbose_name='Fase')),
                ('gender', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='F', max_length=1, verbose_name='Género')),
                ('nacionality', models.CharField(max_length=60, verbose_name='Nacionalidad')),
                ('religion', models.CharField(max_length=60, verbose_name='Religión')),
                ('birthPlace', models.DateField(verbose_name='Lugar de nacimiento')),
                ('status', models.CharField(choices=[('A', 'Activo'), ('B', 'Baja'), ('F', 'Finado')], default='A', max_length=1)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Adulto',
                'verbose_name_plural': 'Adultos',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Caregiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Nombre(s)')),
                ('lastName', models.CharField(max_length=60, verbose_name='Apellido Paterno')),
                ('mLastName', models.CharField(max_length=60, verbose_name='Apellido Materno')),
                ('relationship', models.CharField(choices=[('E', 'Esposo(a)'), ('H', 'Hijo(a)'), ('A', 'Amigo(a)'), ('F', 'Familiar')], default='E', max_length=1, verbose_name='Parentesco')),
                ('email', models.CharField(max_length=100, verbose_name='Correo electrónico')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono/Celular')),
                ('address', models.CharField(max_length=80, verbose_name='Domicilio')),
                ('civilStatus', models.CharField(choices=[('C', 'Casado(a)'), ('D', 'Divorciado(a)'), ('V', 'Viudo(a)'), ('S', 'Soltero(a)'), ('U', 'Unión Libre')], default='S', max_length=1)),
                ('gender', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='F', max_length=1, verbose_name='Género')),
                ('religion', models.CharField(max_length=40, verbose_name='Religión')),
                ('ocupation', models.CharField(max_length=60, verbose_name='Ocupación')),
                ('availability', models.CharField(blank=True, max_length=60, null=True, verbose_name='Tiempo disponible para tratar asuntos relacionados al cuidado del adulto')),
                ('availabilityHome', models.CharField(blank=True, max_length=60, null=True, verbose_name='Tiempo disponible para atención del adulto en casa')),
                ('reason', models.CharField(blank=True, max_length=150, null=True, verbose_name='Razón por la que es el cuidador principal')),
                ('status', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('adult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Adult', verbose_name='Adulto')),
            ],
            options={
                'verbose_name': 'Cuidador',
                'verbose_name_plural': 'Cuidadores',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.CharField(max_length=60, verbose_name='Prueba aún....')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('adult', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='principal.Adult')),
            ],
            options={
                'verbose_name': 'Aplicación de Instrumentos',
                'verbose_name_plural': 'Aplicaciones de Instrumentos',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Nombre(s)')),
                ('lastName', models.CharField(max_length=60, verbose_name='Apellido Paterno')),
                ('mLastName', models.CharField(max_length=60, verbose_name='Apellido Materno')),
                ('relationship', models.CharField(choices=[('E', 'Esposo(a)'), ('H', 'Hijo(a)'), ('A', 'Amigo(a)'), ('F', 'Familiar')], default='E', max_length=1, verbose_name='Parentesco')),
                ('email', models.CharField(max_length=100, verbose_name='Correo electrónico')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono/Celular')),
                ('address', models.CharField(max_length=80, verbose_name='Domicilio')),
                ('gender', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='F', max_length=1, verbose_name='Género')),
                ('reason', models.CharField(blank=True, max_length=150, null=True, verbose_name='Razón por la que es el Tutor')),
                ('knowledge', models.BooleanField(verbose_name='¿Conoce responsabilidades morales y legales que se asumen como tutor?')),
                ('observation', models.CharField(max_length=150, verbose_name='Observaciones')),
                ('status', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('adult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Adult', verbose_name='Adulto')),
            ],
            options={
                'verbose_name': 'Tutor',
                'verbose_name_plural': 'Tutores',
                'ordering': ['-created'],
            },
        ),
    ]
