# Generated by Django 2.1.1 on 2018-09-11 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0008_adult_caregiver_interview_tutor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interview',
            options={'ordering': ['-created'], 'verbose_name': 'Entrevista inicial', 'verbose_name_plural': 'Entrevistas iniciales'},
        ),
        migrations.AlterField(
            model_name='adult',
            name='birthPlace',
            field=models.CharField(max_length=60, verbose_name='Lugar de nacimiento'),
        ),
        migrations.AlterField(
            model_name='caregiver',
            name='availability',
            field=models.TextField(blank=True, null=True, verbose_name='Tiempo disponible para tratar asuntos relacionados al cuidado del adulto'),
        ),
        migrations.AlterField(
            model_name='caregiver',
            name='availabilityHome',
            field=models.TextField(blank=True, null=True, verbose_name='Tiempo disponible para atención del adulto en casa'),
        ),
        migrations.AlterField(
            model_name='caregiver',
            name='reason',
            field=models.TextField(blank=True, null=True, verbose_name='Razón por la que es el cuidador principal'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='observation',
            field=models.TextField(verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='reason',
            field=models.TextField(blank=True, null=True, verbose_name='Razón por la que es el Tutor'),
        ),
    ]
