# Generated by Django 2.1.1 on 2018-09-11 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0009_auto_20180910_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentresult',
            name='caregiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.Caregiver'),
        ),
    ]
