# Generated by Django 2.1.1 on 2018-09-15 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0011_auto_20180911_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='style',
            field=models.SmallIntegerField(choices=[(1, 'Misma escala'), ('2', 'Escala por pregunta')], default=1, verbose_name='Tipo de cuestionario'),
        ),
    ]
