# Generated by Django 2.1.1 on 2018-09-17 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0012_instrument_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentresult',
            name='status',
            field=models.CharField(choices=[('A', 'Activo'), ('C', 'Contestado')], default='A', max_length=1),
        ),
    ]
