# Generated by Django 2.1.1 on 2018-09-18 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0013_instrumentresult_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='adult',
            name='isPrincipal',
            field=models.BooleanField(default=True, verbose_name='Cuidador principal'),
        ),
    ]
