# Generated by Django 2.1.1 on 2018-09-18 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0014_adult_isprincipal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adult',
            name='nacionality',
            field=models.CharField(default='Mexicana', max_length=60, verbose_name='Nacionalidad'),
        ),
        migrations.AlterField(
            model_name='adult',
            name='religion',
            field=models.CharField(default='Católica', max_length=60, verbose_name='Religión'),
        ),
    ]
