# Generated by Django 2.1.1 on 2018-09-18 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0015_auto_20180918_0013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adult',
            name='isPrincipal',
        ),
        migrations.AddField(
            model_name='caregiver',
            name='isPrincipal',
            field=models.BooleanField(default=True, verbose_name='Cuidador principal'),
        ),
    ]
